In [1]:
#LSTM for One-Char to One-Char Prediction
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.utils import np_utils

/usr/local/anaconda/python3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [33]:
import numpy
# fix random seed for reproducibility
numpy.random.seed(7)
# define the raw dataset
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
# create mapping of characters to integers (0-25) and the reverse
char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))

In [34]:
# prepare the dataset of input to output pairs encoded as integers
seq_length = 1
dataX = []
dataY = []

In [35]:
type(dataX)

list

In [36]:
for i in range(0, len(alphabet) - seq_length, 1):
    seq_in = alphabet[i:(i + seq_length)]
    seq_out = alphabet[i + seq_length]
    dataX.append([char_to_int[char] for char in seq_in])
    dataY.append(char_to_int[seq_out])
    print(seq_in, '->', seq_out)

A -> B
B -> C
C -> D
D -> E
E -> F
F -> G
G -> H
H -> I
I -> J
J -> K
K -> L
L -> M
M -> N
N -> O
O -> P
P -> Q
Q -> R
R -> S
S -> T
T -> U
U -> V
V -> W
W -> X
X -> Y
Y -> Z


In [37]:
dataX

[[0],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [12],
 [13],
 [14],
 [15],
 [16],
 [17],
 [18],
 [19],
 [20],
 [21],
 [22],
 [23],
 [24]]

In [38]:
# reshape X to be [samples, time steps, features]
X = numpy.reshape(dataX, (len(dataX), seq_length, 1))
X.shape

(25, 1, 1)

In [39]:
# normalize
X = X / float(len(alphabet))
# one hot encode the output variable
y = np_utils.to_categorical(dataY)

In [40]:
y[0]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [41]:
X.shape

(25, 1, 1)

In [42]:
y.shape

(25, 26)

In [44]:
# create and fit the model
model = Sequential()
model.add(LSTM(32, input_shape=(X.shape[1], X.shape[2])))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=500, batch_size=1, verbose=2)

Epoch 1/500
 - 1s - loss: 3.2661 - acc: 0.0000e+00
Epoch 2/500
 - 0s - loss: 3.2582 - acc: 0.0000e+00
Epoch 3/500
 - 0s - loss: 3.2551 - acc: 0.0400
Epoch 4/500
 - 0s - loss: 3.2524 - acc: 0.0400
Epoch 5/500
 - 0s - loss: 3.2495 - acc: 0.0400
Epoch 6/500
 - 0s - loss: 3.2471 - acc: 0.0400
Epoch 7/500
 - 0s - loss: 3.2440 - acc: 0.0400
Epoch 8/500
 - 0s - loss: 3.2412 - acc: 0.0400
Epoch 9/500
 - 0s - loss: 3.2378 - acc: 0.0400
Epoch 10/500
 - 0s - loss: 3.2348 - acc: 0.0400
Epoch 11/500
 - 0s - loss: 3.2313 - acc: 0.0400
Epoch 12/500
 - 0s - loss: 3.2277 - acc: 0.0400
Epoch 13/500
 - 0s - loss: 3.2237 - acc: 0.0400
Epoch 14/500
 - 0s - loss: 3.2203 - acc: 0.0400
Epoch 15/500
 - 0s - loss: 3.2161 - acc: 0.0400
Epoch 16/500
 - 0s - loss: 3.2117 - acc: 0.0400
Epoch 17/500
 - 0s - loss: 3.2066 - acc: 0.0400
Epoch 18/500
 - 0s - loss: 3.2017 - acc: 0.0400
Epoch 19/500
 - 0s - loss: 3.1969 - acc: 0.0400
Epoch 20/500
 - 0s - loss: 3.1911 - acc: 0.0400
Epoch 21/500
 - 0s - loss: 3.1854 - acc: 

 - 0s - loss: 2.2047 - acc: 0.2400
Epoch 171/500
 - 0s - loss: 2.2028 - acc: 0.2800
Epoch 172/500
 - 0s - loss: 2.1987 - acc: 0.3600
Epoch 173/500
 - 0s - loss: 2.1965 - acc: 0.4000
Epoch 174/500
 - 0s - loss: 2.1931 - acc: 0.2800
Epoch 175/500
 - 0s - loss: 2.1909 - acc: 0.2400
Epoch 176/500
 - 0s - loss: 2.1872 - acc: 0.2800
Epoch 177/500
 - 0s - loss: 2.1844 - acc: 0.2800
Epoch 178/500
 - 0s - loss: 2.1817 - acc: 0.3200
Epoch 179/500
 - 0s - loss: 2.1791 - acc: 0.2800
Epoch 180/500
 - 0s - loss: 2.1766 - acc: 0.2800
Epoch 181/500
 - 0s - loss: 2.1727 - acc: 0.2400
Epoch 182/500
 - 0s - loss: 2.1717 - acc: 0.3600
Epoch 183/500
 - 0s - loss: 2.1687 - acc: 0.3600
Epoch 184/500
 - 0s - loss: 2.1652 - acc: 0.3200
Epoch 185/500
 - 0s - loss: 2.1617 - acc: 0.2800
Epoch 186/500
 - 0s - loss: 2.1605 - acc: 0.3600
Epoch 187/500
 - 0s - loss: 2.1578 - acc: 0.3200
Epoch 188/500
 - 0s - loss: 2.1537 - acc: 0.3600
Epoch 189/500
 - 0s - loss: 2.1523 - acc: 0.3600
Epoch 190/500
 - 0s - loss: 2.1505

Epoch 338/500
 - 0s - loss: 1.8803 - acc: 0.6000
Epoch 339/500
 - 0s - loss: 1.8796 - acc: 0.6400
Epoch 340/500
 - 0s - loss: 1.8749 - acc: 0.6400
Epoch 341/500
 - 0s - loss: 1.8761 - acc: 0.6800
Epoch 342/500
 - 0s - loss: 1.8745 - acc: 0.5600
Epoch 343/500
 - 0s - loss: 1.8733 - acc: 0.5200
Epoch 344/500
 - 0s - loss: 1.8701 - acc: 0.6000
Epoch 345/500
 - 0s - loss: 1.8694 - acc: 0.6000
Epoch 346/500
 - 0s - loss: 1.8675 - acc: 0.6400
Epoch 347/500
 - 0s - loss: 1.8662 - acc: 0.5600
Epoch 348/500
 - 0s - loss: 1.8659 - acc: 0.6400
Epoch 349/500
 - 0s - loss: 1.8644 - acc: 0.6000
Epoch 350/500
 - 0s - loss: 1.8633 - acc: 0.6000
Epoch 351/500
 - 0s - loss: 1.8613 - acc: 0.7200
Epoch 352/500
 - 0s - loss: 1.8590 - acc: 0.5200
Epoch 353/500
 - 0s - loss: 1.8607 - acc: 0.6400
Epoch 354/500
 - 0s - loss: 1.8575 - acc: 0.6800
Epoch 355/500
 - 0s - loss: 1.8557 - acc: 0.6000
Epoch 356/500
 - 0s - loss: 1.8538 - acc: 0.6000
Epoch 357/500
 - 0s - loss: 1.8543 - acc: 0.6400
Epoch 358/500
 - 0s 

In [18]:
# summarize performance of the model
scores = model.evaluate(X, y, verbose=0)
print("Model Accuracy: %.2f%%" % (scores[1]*100))
# demonstrate some model predictions


Model Accuracy: 88.00%


In [19]:
dataX[4]

[4]

In [21]:
#Checking for one sample
test=dataX[4]
test = numpy.reshape(test, (1, len(test), 1))
test = test / float(len(alphabet))
pred = model.predict(test, verbose=0)
pred

array([[7.9197704e-08, 3.4296943e-03, 3.8385671e-02, 1.2224563e-01,
        2.0145595e-01, 2.2066437e-01, 1.7941871e-01, 1.1342851e-01,
        6.6053510e-02, 3.1575523e-02, 1.4205774e-02, 5.9139552e-03,
        2.0756808e-03, 7.4992678e-04, 2.6653905e-04, 9.2368275e-05,
        2.7628272e-05, 7.8405246e-06, 1.8602891e-06, 5.9656065e-07,
        1.4036341e-07, 2.8747261e-08, 6.8794863e-09, 1.1505397e-09,
        3.2796257e-10, 5.9433118e-11]], dtype=float32)

In [22]:
ind = numpy.argmax(pred)
res = int_to_char[ind]
res

'F'

In [23]:
for pattern in dataX:
    x = numpy.reshape(pattern, (1, len(pattern), 1))
    x = x / float(len(alphabet))
    prediction = model.predict(x, verbose=0)
    index = numpy.argmax(prediction)
    result = int_to_char[index]
    seq_in = [int_to_char[value] for value in pattern]
    print(seq_in, "->", result)

['A'] -> B
['B'] -> B
['C'] -> D
['D'] -> E
['E'] -> F
['F'] -> G
['G'] -> H
['H'] -> I
['I'] -> J
['J'] -> K
['K'] -> L
['L'] -> M
['M'] -> N
['N'] -> O
['O'] -> P
['P'] -> Q
['Q'] -> R
['R'] -> S
['S'] -> T
['T'] -> U
['U'] -> V
['V'] -> W
['W'] -> Y
['X'] -> Z
['Y'] -> Z


In [23]:
#LSTM to learn three-char time steps to one-char mapping
import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.utils import np_utils
# fix random seed for reproducibility
numpy.random.seed(7)
# define the raw dataset
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
# create mapping of characters to integers (0-25) and the reverse
char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))
# prepare the dataset of input to output pairs encoded as integers
seq_length = 3
dataX = []
dataY = []
for i in range(0, len(alphabet) - seq_length, 1):
    seq_in = alphabet[i:i + seq_length]
    seq_out = alphabet[i + seq_length]
    dataX.append([char_to_int[char] for char in seq_in])
    dataY.append(char_to_int[seq_out])
    print(seq_in, '->', seq_out)
# reshape X to be [samples, time steps, features]
X = numpy.reshape(dataX, (len(dataX), seq_length, 1))


ABC -> D
BCD -> E
CDE -> F
DEF -> G
EFG -> H
FGH -> I
GHI -> J
HIJ -> K
IJK -> L
JKL -> M
KLM -> N
LMN -> O
MNO -> P
NOP -> Q
OPQ -> R
PQR -> S
QRS -> T
RST -> U
STU -> V
TUV -> W
UVW -> X
VWX -> Y
WXY -> Z


In [24]:
X.shape

(23, 3, 1)

In [25]:
X

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 1],
        [ 2],
        [ 3]],

       [[ 2],
        [ 3],
        [ 4]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 7],
        [ 8],
        [ 9]],

       [[ 8],
        [ 9],
        [10]],

       [[ 9],
        [10],
        [11]],

       [[10],
        [11],
        [12]],

       [[11],
        [12],
        [13]],

       [[12],
        [13],
        [14]],

       [[13],
        [14],
        [15]],

       [[14],
        [15],
        [16]],

       [[15],
        [16],
        [17]],

       [[16],
        [17],
        [18]],

       [[17],
        [18],
        [19]],

       [[18],
        [19],
        [20]],

       [[19],
        [20],
        [21]],

       [[20],
        [21],
        [22]],

       [[21],
        [22],
        [23]],

       [[22],
        [23],
    

In [26]:
# normalize
X = X / float(len(alphabet))
X

array([[[0.        ],
        [0.03846154],
        [0.07692308]],

       [[0.03846154],
        [0.07692308],
        [0.11538462]],

       [[0.07692308],
        [0.11538462],
        [0.15384615]],

       [[0.11538462],
        [0.15384615],
        [0.19230769]],

       [[0.15384615],
        [0.19230769],
        [0.23076923]],

       [[0.19230769],
        [0.23076923],
        [0.26923077]],

       [[0.23076923],
        [0.26923077],
        [0.30769231]],

       [[0.26923077],
        [0.30769231],
        [0.34615385]],

       [[0.30769231],
        [0.34615385],
        [0.38461538]],

       [[0.34615385],
        [0.38461538],
        [0.42307692]],

       [[0.38461538],
        [0.42307692],
        [0.46153846]],

       [[0.42307692],
        [0.46153846],
        [0.5       ]],

       [[0.46153846],
        [0.5       ],
        [0.53846154]],

       [[0.5       ],
        [0.53846154],
        [0.57692308]],

       [[0.53846154],
        [0.57692308],
    

In [27]:
# one hot encode the output variable
y = np_utils.to_categorical(dataY)
# create and fit the model
model = Sequential()
model.add(LSTM(32, input_shape=(X.shape[1], X.shape[2])))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=500, batch_size=1, verbose=2)
# summarize performance of the model
scores = model.evaluate(X, y, verbose=0)
print("Model Accuracy: %.2f%%" % (scores[1]*100))
# demonstrate some model predictions
for pattern in dataX:
    x = numpy.reshape(pattern, (1, len(pattern), 1))
    x = x / float(len(alphabet))
    prediction = model.predict(x, verbose=0)
    index = numpy.argmax(prediction)
    result = int_to_char[index]
    seq_in = [int_to_char[value] for value in pattern]
    print(seq_in, "->", result)

Epoch 1/500
 - 1s - loss: 3.2701 - acc: 0.0000e+00
Epoch 2/500
 - 0s - loss: 3.2547 - acc: 0.0000e+00
Epoch 3/500
 - 0s - loss: 3.2465 - acc: 0.0000e+00
Epoch 4/500
 - 0s - loss: 3.2393 - acc: 0.0435
Epoch 5/500
 - 0s - loss: 3.2313 - acc: 0.0435
Epoch 6/500
 - 0s - loss: 3.2230 - acc: 0.0435
Epoch 7/500
 - 0s - loss: 3.2142 - acc: 0.0435
Epoch 8/500
 - 0s - loss: 3.2052 - acc: 0.0435
Epoch 9/500
 - 0s - loss: 3.1940 - acc: 0.0435
Epoch 10/500
 - 0s - loss: 3.1822 - acc: 0.0435
Epoch 11/500
 - 0s - loss: 3.1702 - acc: 0.0435
Epoch 12/500
 - 0s - loss: 3.1555 - acc: 0.0435
Epoch 13/500
 - 0s - loss: 3.1398 - acc: 0.0435
Epoch 14/500
 - 0s - loss: 3.1239 - acc: 0.0435
Epoch 15/500
 - 0s - loss: 3.1062 - acc: 0.0435
Epoch 16/500
 - 0s - loss: 3.0885 - acc: 0.0000e+00
Epoch 17/500
 - 0s - loss: 3.0723 - acc: 0.0000e+00
Epoch 18/500
 - 0s - loss: 3.0584 - acc: 0.0435
Epoch 19/500
 - 0s - loss: 3.0381 - acc: 0.0435
Epoch 20/500
 - 0s - loss: 3.0210 - acc: 0.0870
Epoch 21/500
 - 0s - loss: 3.

Epoch 170/500
 - 0s - loss: 1.0949 - acc: 0.9130
Epoch 171/500
 - 0s - loss: 1.0844 - acc: 0.9565
Epoch 172/500
 - 0s - loss: 1.0845 - acc: 0.8696
Epoch 173/500
 - 0s - loss: 1.0734 - acc: 0.9565
Epoch 174/500
 - 0s - loss: 1.0772 - acc: 0.8696
Epoch 175/500
 - 0s - loss: 1.0665 - acc: 0.8696
Epoch 176/500
 - 0s - loss: 1.0592 - acc: 0.8696
Epoch 177/500
 - 0s - loss: 1.0556 - acc: 0.9130
Epoch 178/500
 - 0s - loss: 1.0568 - acc: 0.8696
Epoch 179/500
 - 0s - loss: 1.0401 - acc: 0.9130
Epoch 180/500
 - 0s - loss: 1.0372 - acc: 0.9130
Epoch 181/500
 - 0s - loss: 1.0363 - acc: 0.9565
Epoch 182/500
 - 0s - loss: 1.0261 - acc: 0.9130
Epoch 183/500
 - 0s - loss: 1.0220 - acc: 0.9130
Epoch 184/500
 - 0s - loss: 1.0209 - acc: 0.9130
Epoch 185/500
 - 0s - loss: 1.0124 - acc: 0.8696
Epoch 186/500
 - 0s - loss: 1.0073 - acc: 0.9130
Epoch 187/500
 - 0s - loss: 1.0010 - acc: 0.9130
Epoch 188/500
 - 0s - loss: 0.9984 - acc: 0.9565
Epoch 189/500
 - 0s - loss: 0.9943 - acc: 0.9565
Epoch 190/500
 - 0s 

 - 0s - loss: 0.4576 - acc: 0.9565
Epoch 338/500
 - 0s - loss: 0.4577 - acc: 0.9565
Epoch 339/500
 - 0s - loss: 0.4650 - acc: 1.0000
Epoch 340/500
 - 0s - loss: 0.4573 - acc: 0.9565
Epoch 341/500
 - 0s - loss: 0.4487 - acc: 1.0000
Epoch 342/500
 - 0s - loss: 0.4517 - acc: 1.0000
Epoch 343/500
 - 0s - loss: 0.4482 - acc: 1.0000
Epoch 344/500
 - 0s - loss: 0.4416 - acc: 0.9565
Epoch 345/500
 - 0s - loss: 0.4328 - acc: 1.0000
Epoch 346/500
 - 0s - loss: 0.4307 - acc: 1.0000
Epoch 347/500
 - 0s - loss: 0.4325 - acc: 1.0000
Epoch 348/500
 - 0s - loss: 0.4268 - acc: 1.0000
Epoch 349/500
 - 0s - loss: 0.4352 - acc: 1.0000
Epoch 350/500
 - 0s - loss: 0.4295 - acc: 1.0000
Epoch 351/500
 - 0s - loss: 0.4213 - acc: 1.0000
Epoch 352/500
 - 0s - loss: 0.4223 - acc: 0.9565
Epoch 353/500
 - 0s - loss: 0.4168 - acc: 1.0000
Epoch 354/500
 - 0s - loss: 0.4178 - acc: 1.0000
Epoch 355/500
 - 0s - loss: 0.4143 - acc: 1.0000
Epoch 356/500
 - 0s - loss: 0.4121 - acc: 1.0000
Epoch 357/500
 - 0s - loss: 0.4119

['N', 'O', 'P'] -> Q
['O', 'P', 'Q'] -> R
['P', 'Q', 'R'] -> S
['Q', 'R', 'S'] -> T
['R', 'S', 'T'] -> U
['S', 'T', 'U'] -> V
['T', 'U', 'V'] -> W
['U', 'V', 'W'] -> X
['V', 'W', 'X'] -> Y
['W', 'X', 'Y'] -> Z


In [28]:
# demonstrate predicting random patterns
print("Test a Random Pattern:")
for i in range(0,20): 
    pattern_index = numpy.random.randint(len(dataX))
    pattern = dataX[pattern_index]
    x = numpy.reshape(pattern, (1, len(pattern), 1))
    x = x / float(len(alphabet))
    prediction = model.predict(x, verbose=0)
    index = numpy.argmax(prediction)
    result = int_to_char[index]
    seq_in = [int_to_char[value] for value in pattern]
    print(seq_in, "->", result)

Test a Random Pattern:
['F', 'G', 'H'] -> I
['D', 'E', 'F'] -> G
['H', 'I', 'J'] -> K
['I', 'J', 'K'] -> L
['T', 'U', 'V'] -> W
['H', 'I', 'J'] -> K
['V', 'W', 'X'] -> Y
['T', 'U', 'V'] -> W
['M', 'N', 'O'] -> P
['H', 'I', 'J'] -> K
['T', 'U', 'V'] -> W
['D', 'E', 'F'] -> G
['W', 'X', 'Y'] -> Z
['N', 'O', 'P'] -> Q
['S', 'T', 'U'] -> V
['H', 'I', 'J'] -> K
['D', 'E', 'F'] -> G
['J', 'K', 'L'] -> M
['I', 'J', 'K'] -> L
['M', 'N', 'O'] -> P


In [29]:
# LSTM with Variable Length Input Sequences to One Character Output
import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.utils import np_utils
from keras.preprocessing.sequence import pad_sequences

In [45]:
# fix random seed for reproducibility
numpy.random.seed(7)
# define the raw dataset
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
# create mapping of characters to integers (0-25) and the reverse
char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))
# prepare the dataset of input to output pairs encoded as integers
num_inputs = 1000
max_len = 5 #Maximum Input Sequence Length
dataX = []
dataY = []
for i in range(num_inputs):
    start = numpy.random.randint(len(alphabet)-2)
    end = numpy.random.randint(start, min(start+max_len,len(alphabet)-1))
    sequence_in = alphabet[start:end+1]
    sequence_out = alphabet[end + 1]
    dataX.append([char_to_int[char] for char in sequence_in])
    dataY.append(char_to_int[sequence_out])
    print(sequence_in, '->', sequence_out)


PQRST -> U
W -> X
O -> P
OPQ -> R
IJKLM -> N
QRSTU -> V
ABCD -> E
X -> Y
GHIJ -> K
M -> N
XY -> Z
QRST -> U
ABC -> D
JKLMN -> O
OP -> Q
XY -> Z
D -> E
T -> U
B -> C
QRSTU -> V
HIJ -> K
JKLM -> N
ABCDE -> F
X -> Y
V -> W
DE -> F
DEFG -> H
BCDE -> F
EFGH -> I
BCDE -> F
FG -> H
RST -> U
TUV -> W
STUV -> W
LMN -> O
P -> Q
MNOP -> Q
JK -> L
MNOP -> Q
OPQRS -> T
UVWXY -> Z
PQRS -> T
D -> E
EFGH -> I
IJK -> L
WX -> Y
STUV -> W
MNOPQ -> R
P -> Q
WXY -> Z
VWX -> Y
V -> W
HI -> J
KLMNO -> P
UV -> W
JKL -> M
ABCDE -> F
WXY -> Z
M -> N
CDEF -> G
KLMNO -> P
RST -> U
RS -> T
W -> X
J -> K
WX -> Y
JKLMN -> O
MN -> O
L -> M
BCDE -> F
TU -> V
MNOPQ -> R
NOPQR -> S
HIJ -> K
JKLM -> N
STUVW -> X
QRST -> U
N -> O
VWXY -> Z
B -> C
UVWX -> Y
OP -> Q
K -> L
C -> D
X -> Y
ST -> U
JKLM -> N
B -> C
QR -> S
RS -> T
VWXY -> Z
S -> T
NOP -> Q
KLMNO -> P
IJ -> K
EF -> G
MNOP -> Q
WXY -> Z
HI -> J
P -> Q
STUVW -> X
Q -> R
MN -> O
O -> P
C -> D
L -> M
JKLM -> N
K -> L
IJKLM -> N
FGHIJ -> K
LM -> N
OPQ -> R
U -> V
HIJ

In [46]:
# convert list of lists to array and pad sequences if needed
X = pad_sequences(dataX, maxlen=max_len, dtype='float32')
# reshape X to be [samples, time steps, features]
X = numpy.reshape(X, (X.shape[0], max_len, 1))
X

array([[[15.],
        [16.],
        [17.],
        [18.],
        [19.]],

       [[ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [22.]],

       [[ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [14.]],

       ...,

       [[ 0.],
        [18.],
        [19.],
        [20.],
        [21.]],

       [[19.],
        [20.],
        [21.],
        [22.],
        [23.]],

       [[ 0.],
        [17.],
        [18.],
        [19.],
        [20.]]], dtype=float32)

In [47]:
X.shape

(1000, 5, 1)

In [48]:
# normalize
X = X / float(len(alphabet))
# one hot encode the output variable
y = np_utils.to_categorical(dataY)
# create and fit the model
batch_size = 1
model = Sequential()
model.add(LSTM(32, input_shape=(X.shape[1], 1)))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=100, batch_size=batch_size, verbose=2)
# summarize performance of the model
scores = model.evaluate(X, y, verbose=0)
print("Model Accuracy: %.2f%%" % (scores[1]*100))
# demonstrate some model predictions
for i in range(20):
    pattern_index = numpy.random.randint(len(dataX))
    pattern = dataX[pattern_index]
    x = pad_sequences([pattern], maxlen=max_len, dtype='float32')
    x = numpy.reshape(x, (1, max_len, 1))
    x = x / float(len(alphabet))
    prediction = model.predict(x, verbose=0)
    index = numpy.argmax(prediction)
    result = int_to_char[index]
    seq_in = [int_to_char[value] for value in pattern]
    print(seq_in, "->", result)

Epoch 1/500
 - 6s - loss: 3.0782 - acc: 0.0640
Epoch 2/500
 - 5s - loss: 2.7660 - acc: 0.1300
Epoch 3/500
 - 5s - loss: 2.4372 - acc: 0.1950
Epoch 4/500
 - 5s - loss: 2.2110 - acc: 0.2640
Epoch 5/500
 - 5s - loss: 2.0613 - acc: 0.3100
Epoch 6/500
 - 5s - loss: 1.9386 - acc: 0.3250
Epoch 7/500
 - 5s - loss: 1.8371 - acc: 0.3460
Epoch 8/500
 - 5s - loss: 1.7532 - acc: 0.3800
Epoch 9/500
 - 5s - loss: 1.6749 - acc: 0.4200
Epoch 10/500
 - 5s - loss: 1.6023 - acc: 0.4450
Epoch 11/500
 - 5s - loss: 1.5333 - acc: 0.4690
Epoch 12/500
 - 5s - loss: 1.4742 - acc: 0.4930
Epoch 13/500
 - 5s - loss: 1.4207 - acc: 0.5090
Epoch 14/500
 - 5s - loss: 1.3640 - acc: 0.5480
Epoch 15/500
 - 5s - loss: 1.3213 - acc: 0.5570
Epoch 16/500
 - 5s - loss: 1.2732 - acc: 0.5850
Epoch 17/500
 - 5s - loss: 1.2288 - acc: 0.5880
Epoch 18/500
 - 5s - loss: 1.1956 - acc: 0.6200
Epoch 19/500
 - 5s - loss: 1.1494 - acc: 0.6190
Epoch 20/500
 - 5s - loss: 1.1210 - acc: 0.6380
Epoch 21/500
 - 5s - loss: 1.0849 - acc: 0.6520
E

Epoch 171/500
 - 5s - loss: 0.2567 - acc: 0.9230
Epoch 172/500
 - 5s - loss: 0.2612 - acc: 0.9230
Epoch 173/500
 - 5s - loss: 0.2522 - acc: 0.9220
Epoch 174/500
 - 5s - loss: 0.4207 - acc: 0.8790
Epoch 175/500
 - 5s - loss: 0.2394 - acc: 0.9290
Epoch 176/500
 - 5s - loss: 0.2440 - acc: 0.9240
Epoch 177/500
 - 5s - loss: 0.2452 - acc: 0.9290
Epoch 178/500
 - 5s - loss: 0.2579 - acc: 0.9220
Epoch 179/500
 - 5s - loss: 0.3551 - acc: 0.8890
Epoch 180/500
 - 5s - loss: 0.2383 - acc: 0.9240
Epoch 181/500
 - 5s - loss: 0.2399 - acc: 0.9350
Epoch 182/500
 - 5s - loss: 0.2427 - acc: 0.9310
Epoch 183/500
 - 5s - loss: 0.2427 - acc: 0.9320
Epoch 184/500
 - 5s - loss: 0.2465 - acc: 0.9260
Epoch 185/500
 - 5s - loss: 0.3826 - acc: 0.8780
Epoch 186/500
 - 5s - loss: 0.2294 - acc: 0.9390
Epoch 187/500
 - 5s - loss: 0.2292 - acc: 0.9400
Epoch 188/500
 - 5s - loss: 0.2302 - acc: 0.9290
Epoch 189/500
 - 5s - loss: 0.2390 - acc: 0.9340
Epoch 190/500
 - 5s - loss: 0.2836 - acc: 0.9210
Epoch 191/500
 - 5s 

 - 5s - loss: 0.1353 - acc: 0.9670
Epoch 339/500
 - 5s - loss: 0.1359 - acc: 0.9670
Epoch 340/500
 - 5s - loss: 0.1390 - acc: 0.9670
Epoch 341/500
 - 5s - loss: 0.2516 - acc: 0.9400
Epoch 342/500
 - 5s - loss: 0.1959 - acc: 0.9600
Epoch 343/500
 - 5s - loss: 0.1338 - acc: 0.9710
Epoch 344/500
 - 5s - loss: 0.1355 - acc: 0.9660
Epoch 345/500
 - 5s - loss: 0.1361 - acc: 0.9710
Epoch 346/500
 - 5s - loss: 0.1362 - acc: 0.9600
Epoch 347/500
 - 5s - loss: 0.1386 - acc: 0.9660
Epoch 348/500
 - 5s - loss: 0.1375 - acc: 0.9650
Epoch 349/500
 - 5s - loss: 0.1599 - acc: 0.9500
Epoch 350/500
 - 5s - loss: 0.2031 - acc: 0.9490
Epoch 351/500
 - 5s - loss: 0.1302 - acc: 0.9680
Epoch 352/500
 - 5s - loss: 0.1299 - acc: 0.9620
Epoch 353/500
 - 5s - loss: 0.1317 - acc: 0.9690
Epoch 354/500
 - 5s - loss: 0.1306 - acc: 0.9670
Epoch 355/500
 - 5s - loss: 0.1332 - acc: 0.9610
Epoch 356/500
 - 5s - loss: 0.1337 - acc: 0.9630
Epoch 357/500
 - 5s - loss: 0.1669 - acc: 0.9540
Epoch 358/500
 - 5s - loss: 0.2476